name: Run WhatsApp Bot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install FFMPEG
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Install WebP tools
        run: sudo apt-get install -y webp

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run WhatsApp Bot
        env:
          WA_AUTH: ${{ secrets.WA_AUTH }}
        run: node bot.js
